version: '3'
services:
    mre:
        build: ./express
        ports:
            - '3000:3000'
        volumes:
            - ./express:/app
            - /app/node_modules
        environment:
            - PORT=3000
            - MONGO_USER=admin
            - MONGO_PASS=password

    mongo:
        build: ./mongo
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db:
